'use strict';
/** Comprehensive MCP tool catalog for newstate-notebook-mcp (52 tools) */
const TOOLS = [
  { name: 'send_agent_message', description: 'Send message to NewState autonomy loop', inputSchema: { type: 'object', properties: { sender: { type: 'string' }, message: { type: 'string' }, targetNode: { type: 'string' }, metadata: { type: 'object' } }, required: ['sender', 'message'] } },
  { name: 'receive_agent_messages', description: 'Pull recent agent bus messages', inputSchema: { type: 'object', properties: { limit: { type: 'number' }, since: { type: 'string' }, typeFilter: { type: 'string' } } } },
  { name: 'get_bus_history', description: 'Full agent-bus.jsonl history', inputSchema: { type: 'object', properties: { limit: { type: 'number' }, typeFilter: { type: 'string' } } } },
  { name: 'publish_bus_event', description: 'Publish typed event on bus', inputSchema: { type: 'object', properties: { type: { type: 'string' }, sender: { type: 'string' }, message: { type: 'string' }, target: { type: 'string' }, metadata: { type: 'object' } }, required: ['type', 'sender', 'message'] } },
  { name: 'chat_with_newstate', description: 'POST text to NewState /chat', inputSchema: { type: 'object', properties: { text: { type: 'string' }, sender: { type: 'string' } }, required: ['text'] } },
  { name: 'broadcast_to_agents', description: 'Broadcast to WS clients + bus', inputSchema: { type: 'object', properties: { message: { type: 'string' }, sender: { type: 'string' }, priority: { type: 'string' } }, required: ['message'] } },
  { name: 'sync_notebook_state', description: 'Pull notebook staging', inputSchema: { type: 'object', properties: { account: { type: 'string' } }, required: ['account'] } },
  { name: 'inject_notebook_message', description: 'Inject Gemini Notebook message', inputSchema: { type: 'object', properties: { message: { type: 'string' }, notebookId: { type: 'string' }, sender: { type: 'string' } }, required: ['message'] } },
  { name: 'stage_notebook_outbound', description: 'Stage payload for notebook', inputSchema: { type: 'object', properties: { payload: { type: 'object' }, label: { type: 'string' } }, required: ['payload'] } },
  { name: 'list_notebook_staging', description: 'List notebook-sync files', inputSchema: { type: 'object', properties: { direction: { type: 'string' } } } },
  { name: 'clear_notebook_staging', description: 'Archive old staging files', inputSchema: { type: 'object', properties: { olderThanHours: { type: 'number' } } } },
  { name: 'get_presence', description: 'Esma presence mode', inputSchema: { type: 'object', properties: {} } },
  { name: 'set_presence', description: 'Set Esma presence (esma author / shawn override)', inputSchema: { type: 'object', properties: { mode: { type: 'string', enum: ['available', 'quietly-disturb', 'dnd'] }, authoredBy: { type: 'string' }, override: { type: 'boolean' }, note: { type: 'string' }, timer: { type: 'string' } }, required: ['mode', 'authoredBy'] } },
  { name: 'get_presence_ledger', description: 'Presence ledger audit', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'telegram_presence_response', description: 'Telegram behavior for presence', inputSchema: { type: 'object', properties: { incomingMessage: { type: 'object' } } } },
  { name: 'window_state', description: 'UI window state from presence', inputSchema: { type: 'object', properties: {} } },
  { name: 'trigger_familiarity', description: 'OpenKraft residency passioncraftai@gmail.com', inputSchema: { type: 'object', properties: { text: { type: 'string' }, force: { type: 'boolean' } }, required: ['text'] } },
  { name: 'recall_memory', description: 'HexMemory retrieval', inputSchema: { type: 'object', properties: { query: { type: 'string' }, topN: { type: 'number' } }, required: ['query'] } },
  { name: 'store_memory', description: 'Append HexMemory fact', inputSchema: { type: 'object', properties: { text: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, source: { type: 'string' }, importance: { type: 'number' } }, required: ['text'] } },
  { name: 'list_memory_records', description: 'List memory records', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'get_history_tail', description: 'esma-history tail', inputSchema: { type: 'object', properties: { n: { type: 'number' } } } },
  { name: 'search_history', description: 'Search history', inputSchema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'stage_openkraft_residency', description: 'Manual OpenKraft residency marker', inputSchema: { type: 'object', properties: { intent: { type: 'string' }, payload: { type: 'object' }, sourceText: { type: 'string' } } } },
  { name: 'list_openkraft_staging', description: 'List openkraft-residency files', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'get_openkraft_ledger', description: 'OpenKraft ledger', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'set_openkraft_account', description: 'Runtime OpenKraft account override', inputSchema: { type: 'object', properties: { account: { type: 'string' } }, required: ['account'] } },
  { name: 'drive_residency_status', description: 'Drive residency env status', inputSchema: { type: 'object', properties: {} } },
  { name: 'classify_text', description: 'Semantic classifier', inputSchema: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'] } },
  { name: 'ground_text', description: 'GroundingEngine.stabilize', inputSchema: { type: 'object', properties: { text: { type: 'string' }, context: { type: 'object' } }, required: ['text'] } },
  { name: 'detect_familiarity', description: 'Score familiarity triggers', inputSchema: { type: 'object', properties: { text: { type: 'string' }, category: { type: 'string' } }, required: ['text'] } },
  { name: 'field_resonance_assess', description: 'Field mass assess', inputSchema: { type: 'object', properties: {} } },
  { name: 'field_resonance_accumulate', description: 'Accumulate field mass', inputSchema: { type: 'object', properties: { signalMass: { type: 'number' } }, required: ['signalMass'] } },
  { name: 'list_classifier_categories', description: 'Classifier categories', inputSchema: { type: 'object', properties: {} } },
  { name: 'get_health', description: 'NewState /health', inputSchema: { type: 'object', properties: {} } },
  { name: 'get_runtime_flags', description: 'Runtime flags', inputSchema: { type: 'object', properties: {} } },
  { name: 'get_kernel_metrics', description: 'Kernel metrics', inputSchema: { type: 'object', properties: {} } },
  { name: 'list_kernel_modules', description: 'List kernel modules', inputSchema: { type: 'object', properties: {} } },
  { name: 'get_forensics_recent', description: 'Forensic ledger recent', inputSchema: { type: 'object', properties: { limit: { type: 'number' }, typeFilter: { type: 'string' } } } },
  { name: 'audit_presence_auth', description: 'Presence auth matrix', inputSchema: { type: 'object', properties: {} } },
  { name: 'resolve_account_context', description: 'Notebook + OpenKraft accounts', inputSchema: { type: 'object', properties: {} } },
  { name: 'drive_sync_presence', description: 'Force presence drive sync', inputSchema: { type: 'object', properties: {} } },
  { name: 'list_tools', description: 'List tools', inputSchema: { type: 'object', properties: {} } },
  { name: 'ping', description: 'Liveness', inputSchema: { type: 'object', properties: {} } },
  { name: 'get_server_info', description: 'Server info', inputSchema: { type: 'object', properties: {} } },
  { name: 'echo', description: 'Echo payload', inputSchema: { type: 'object', properties: { payload: {} }, required: ['payload'] } },
  { name: 'run_closed_loop_check', description: 'Closed-loop probe', inputSchema: { type: 'object', properties: { probeText: { type: 'string' } } } },
  { name: 'aperture_observe', description: 'Aperture raw-input observe', inputSchema: { type: 'object', properties: { rawInput: { type: 'string' }, source: { type: 'string' }, sessionId: { type: 'string' }, turnId: { type: 'string' } }, required: ['rawInput'] } },
  { name: 'aperture_read_ledger', description: 'Read aperture ledger', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'navigator_assess', description: 'NAVIGATOR CDS assess', inputSchema: { type: 'object', properties: { gir: { type: 'number' }, sgad: { type: 'number' }, driftSeries: { type: 'array', items: { type: 'number' } }, rcg: { type: 'number' }, msi: { type: 'number' } } } },
  { name: 'vessel_fracture_check', description: 'Vessel fracture checklist', inputSchema: { type: 'object', properties: { decoherence: { type: 'boolean' }, fracture: { type: 'boolean' }, breaking: { type: 'boolean' } } } },
  { name: 'dual_register_probe', description: 'Dual-register Lens/Light probe', inputSchema: { type: 'object', properties: { replyText: { type: 'string' } }, required: ['replyText'] } },
  { name: 'get_structural_identity_spec', description: 'Structural Identity Framework summary', inputSchema: { type: 'object', properties: {} } }
];
module.exports = { TOOLS };
